trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
  
  # ======================
  # .NET SETUP
  # ======================
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: '10.x'
  
  # ======================
  # RESTORE
  # ======================
  - script: dotnet restore OrderProcessing.sln
    displayName: Restore
  
  # ======================
  # BUILD
  # ======================
  - script: dotnet build OrderProcessing.sln -c $(buildConfiguration) --no-restore
    displayName: Build
  
  # ======================
  # TESTS
  # ======================
  # - script: dotnet test OrderProcessing.sln -c Release --no-build
  #   displayName: Test
  
  # ======================
  # PUBLISH API
  # ======================
  - script: dotnet publish OrderProcessing.API/OrderProcessing.API.csproj -c $(buildConfiguration) --no-build -o $(Build.ArtifactStagingDirectory)/api
    displayName: Publish API
  
  # ======================
  # PUBLISH WORKER
  # ======================
  - script: dotnet publish OrderProcessing.Worker/OrderProcessing.Worker.csproj -c $(buildConfiguration) --no-build -o $(Build.ArtifactStagingDirectory)/worker
    displayName: Publish Worker
  
  # ======================
  # ARTIFACT
  # ======================
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop