trigger:
  - main

pool:
  name: Default

variables:
  buildConfiguration: Release
  dockerUser: senseilimao1
  apiImage: orderprocessing-api
  workerImage: orderprocessing-worker
  resourceGroup: rg-order
  apiContainerApp: order-api
  workerContainerApp: order-worker

steps:
  
  # ======================
  # LOGIN DOCKER HUB
  # ======================
  - script: echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USER) --password-stdin
    displayName: Docker Login
  
  # ======================
  # BUILD & PUSH API
  # ======================
  - script: |
      docker build --platform linux/amd64 -t $(dockerUser)/$(apiImage):$(Build.BuildId) -f OrderProcessing.API/Dockerfile .
      docker push $(dockerUser)/$(apiImage):$(Build.BuildId)
    displayName: Build & Push API

  # ======================
  # BUILD & PUSH WORKER
  # ======================
  - script: |
      docker build --platform linux/amd64 -t $(dockerUser)/$(workerImage):$(Build.BuildId) -f OrderProcessing.Worker/Dockerfile .
      docker push $(dockerUser)/$(workerImage):$(Build.BuildId)
    displayName: Build & Push Worker

  # ======================
  # DEPLOY API
  # ======================
  - script: |
      az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
      az containerapp update \
        --name $(apiContainerApp) \
        --resource-group $(resourceGroup) \
        --image $(dockerUser)/$(apiImage):$(Build.BuildId)
    displayName: Deploy API to Azure Container Apps

  # ======================
  # DEPLOY WORKER
  # ======================
  - script: |
      az containerapp update \
        --name $(workerContainerApp) \
        --resource-group $(resourceGroup) \
        --image $(dockerUser)/$(workerImage):$(Build.BuildId)
    displayName: Deploy Worker to Azure Container Apps