trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release
  dockerUser: senseilimao1
  apiImage: orderprocessing-api
  workerImage: orderprocessing-worker
  resourceGroup: rg-order
  apiContainerApp: order-api
  workerContainerApp: order-worker

steps:

  # ======================
  # BUILD & TEST
  # ======================
  - script: dotnet build --configuration Release
    displayName: Build Solution

  - script: |
      dotnet test OrderProcessing.UnitTests/OrderProcessing.UnitTests.csproj --no-build --configuration Release --logger trx --results-directory $(Agent.TempDirectory)
      dotnet test OrderProcessing.IntegrationTests/OrderProcessing.IntegrationTests.csproj --no-build --configuration Release --logger trx --results-directory $(Agent.TempDirectory)
    displayName: Run Tests

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '$(Agent.TempDirectory)/*.trx'
    displayName: Publish Test Results
    condition: always()

  # ======================
  # BUILD & PUSH DOCKER IMAGES
  # ======================
  - script: |
      echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USER) --password-stdin
      docker build --platform linux/amd64 -t $(dockerUser)/$(apiImage):$(Build.BuildId) -f OrderProcessing.API/Dockerfile .
      docker push $(dockerUser)/$(apiImage):$(Build.BuildId)
      docker build --platform linux/amd64 -t $(dockerUser)/$(workerImage):$(Build.BuildId) -f OrderProcessing.Worker/Dockerfile .
      docker push $(dockerUser)/$(workerImage):$(Build.BuildId)
    displayName: Build & Push Docker Images

  # ======================
  # DEPLOY TO AZURE CONTAINER APPS
  # ======================
  - script: |
      az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
      az containerapp update \
        --name $(apiContainerApp) \
        --resource-group $(resourceGroup) \
        --image $(dockerUser)/$(apiImage):$(Build.BuildId)
      az containerapp update \
        --name $(workerContainerApp) \
        --resource-group $(resourceGroup) \
        --image $(dockerUser)/$(workerImage):$(Build.BuildId)
    displayName: Deploy to Azure Container Apps

  # ======================
  # BUILD FRONTEND
  # ======================
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: Setup Node.js

  - script: |
      npm ci
      npm run build
    workingDirectory: OrderProcessing-front
    env:
      VITE_API_URL: https://order-api.wittyhill-1ef4ba1e.eastus2.azurecontainerapps.io
    displayName: Build Frontend

  # ======================
  # DEPLOY FRONTEND
  # ======================
  - script: |
      npm install -g @azure/static-web-apps-cli
      swa deploy ./dist \
        --deployment-token $(AZURE_STATIC_WEB_APPS_TOKEN) \
        --env production
    workingDirectory: OrderProcessing-front
    displayName: Deploy Frontend to Azure Static Web Apps